<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>DataLayer</RootNamespace>
    <AssemblyName>DataLayer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Startup\Internal\BlogsContentSimple.xml">
      <LogicalName>DataLayer.Startup.Internal.BlogsContentSimple.xml</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Startup\Internal\BlogsContextMedium.xml">
      <LogicalName>DataLayer.Startup.Internal.BlogsContextMedium.xml</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GenericLibsBase\GenericLibsBase.csproj" />
    <ProjectReference Include="..\GenericServices\GenericServices.csproj" />
  </ItemGroup>

</Project>
