<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>ServiceLayer</RootNamespace>
    <AssemblyName>ServiceLayer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GenericLibsBase\GenericLibsBase.csproj" />
    <ProjectReference Include="..\GenericServices\GenericServices.csproj" />
    <ProjectReference Include="..\DataLayer\DataLayer.csproj" />
  </ItemGroup>

</Project>
